### ISSUE TITLE
Error to start pvc-tui  with python2.7 or 3.5

### ISSUE THREAD

**Issue by mario-ezquerro** [dnaeon/pvc#21]
HI:
I use virtualenv: am now able to pip install pvc but when I run pvc-tui I get the following:

Traceback (most recent call last):
  File "./pvc-tui", line 39, in <module>
    main()
  File "./pvc-tui", line 35, in main
    app = MainApp()
  File "/home/pvc/pvc-venc/local/lib/python2.7/site-packages/pvc/core.py", line 63, in **init**
    self.dialog = Dialog(autowidgetsize=True)
  File "/home/pvc/pvc-venc/local/lib/python2.7/site-packages/dialog.py", line 1015, in **init**
    self._dialog_prg = _path_to_executable(dialog)
  File "/home/pvc/pvc-venc/local/lib/python2.7/site-packages/dialog.py", line 479, in _path_to_executable
    "can't find the executable for the dialog-like "
dialog.ExecutableNotFound
###### #And If I use phython3

pvc-tui 
Traceback (most recent call last):
  File "/home/pvc/pvc-venv3/bin/pvc-tui", line 39, in <module>
    main()
  File "/home/pvc/pvc-venv3/bin/pvc-tui", line 35, in main
    app = MainApp()
  File "/home/pvc/pvc-venv3/lib/python3.5/site-packages/pvc/core.py", line 63, in **init**
    self.dialog = Dialog(autowidgetsize=True)
  File "/home/pvc/pvc-venv3/lib/python3.5/site-packages/dialog.py", line 998, in **init**
    self._dialog_prg = _path_to_executable(dialog)
  File "/home/pvc/pvc-venv3/lib/python3.5/site-packages/dialog.py", line 469, in _path_to_executable
    "can't find the executable for the dialog-like "
dialog.ExecutableNotFound: Executable not found: can't find the executable for the dialog-like program

**Comment by dnaeon** [comment]
Hey @wbugbofh,

You need to make sure to install [dialog](http://invisible-island.net/dialog/) on your system first.

You should have it already packaged for your system.

Regards,
Marin

**Comment by wbugbofh** [comment]
The pip command
pip show python2-pythondialog
---
Name: python2-pythondialog
Version: 3.4.0

Do I need another version ?

**Comment by mario-ezquerro** [comment]
OK I see the mistake...
The dialog system is not the dialog module python..
ok 
Close.
