### ISSUE TITLE
invalid syntax during pip install

### ISSUE THREAD

**Issue by lamw** [dnaeon/pvc#4]
```
┌─[lamw] - [~] - [2015-04-13 06:49:29]
└─[0] pip install pvc
Requirement already satisfied (use --upgrade to upgrade): pvc in /Library/Python/2.7/site-packages/pvc-0.1.1-py2.7.egg
Downloading/unpacking humanize>=0.5.1 (from pvc)
  Running setup.py egg_info for package humanize

Downloading/unpacking pythondialog>=3.2.1 (from pvc)
  Running setup.py egg_info for package pythondialog
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/Users/lamw/build/pythondialog/setup.py", line 39
        print(traceback.format_exc(), file=sys.stderr)
                                          ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/Users/lamw/build/pythondialog/setup.py", line 39

    print(traceback.format_exc(), file=sys.stderr)

                                      ^
SyntaxError: invalid syntax
```

**Comment by michaelrice** [comment]
@lamw  The requirements say to use python 3. Looks like youre using 2.7.x that could be it

**Comment by lamw** [comment]
@michaelrice I actually have Python3 installed but maybe its some how referencing the old libs, looking for some guidance.

```
└─[1] python -V
Python 3.4.3
```

**Comment by michaelrice** [comment]
@lamw but

```
┌─[lamw] - [~] - [2015-04-13 06:49:29]
└─[0] pip install pvc
Requirement already satisfied (use --upgrade to upgrade): pvc in /Library/Python/2.7/site-packages/pvc-0.1.1-py2.7.egg
```

So somehow python 2.7 is involved right? Did you install it at some point, or maybe your pip is pointing at the wrong pip?

**Comment by dnaeon** [comment]
@lamw, looks like your `pip` is pointing to the Python 2.7 version.

I will close this issue as it is not related to a bug in PVC.
