### ISSUE TITLE
Unexpected crash when a timeout to vcenter happens

### ISSUE THREAD

**Issue by michaelrice** [dnaeon/pvc#6]
I have a networking issue blocking me from hitting my vcenter, but I would expect pvc to handle that gracefully. Instead Im getting this:

```
ERROR:root:Cannot connect to 10.xx.xx.xx: ('Connection aborted.', TimeoutError(60, 'Operation timed out'))
Traceback (most recent call last):
  File "/Users/errr/venvs/pvc/lib/python3.3/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/Users/errr/venvs/pvc/lib/python3.3/site-packages/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "/Users/errr/venvs/pvc/lib/python3.3/site-packages/requests/packages/urllib3/connectionpool.py", line 762, in _validate_conn
    conn.connect()
  File "/Users/errr/venvs/pvc/lib/python3.3/site-packages/requests/packages/urllib3/connection.py", line 204, in connect
    conn = self._new_conn()
  File "/Users/errr/venvs/pvc/lib/python3.3/site-packages/requests/packages/urllib3/connection.py", line 134, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Users/errr/venvs/pvc/lib/python3.3/site-packages/requests/packages/urllib3/util/connection.py", line 88, in create_connection
    raise err
  File "/Users/errr/venvs/pvc/lib/python3.3/site-packages/requests/packages/urllib3/util/connection.py", line 78, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/errr/venvs/pvc/lib/python3.3/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/Users/errr/venvs/pvc/lib/python3.3/site-packages/requests/packages/urllib3/connectionpool.py", line 597, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/errr/venvs/pvc/lib/python3.3/site-packages/requests/packages/urllib3/util/retry.py", line 245, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/errr/venvs/pvc/lib/python3.3/site-packages/requests/packages/urllib3/packages/six.py", line 309, in reraise
    raise value.with_traceback(tb)
  File "/Users/errr/venvs/pvc/lib/python3.3/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/Users/errr/venvs/pvc/lib/python3.3/site-packages/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "/Users/errr/venvs/pvc/lib/python3.3/site-packages/requests/packages/urllib3/connectionpool.py", line 762, in _validate_conn
    conn.connect()
  File "/Users/errr/venvs/pvc/lib/python3.3/site-packages/requests/packages/urllib3/connection.py", line 204, in connect
    conn = self._new_conn()
  File "/Users/errr/venvs/pvc/lib/python3.3/site-packages/requests/packages/urllib3/connection.py", line 134, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Users/errr/venvs/pvc/lib/python3.3/site-packages/requests/packages/urllib3/util/connection.py", line 88, in create_connection
    raise err
  File "/Users/errr/venvs/pvc/lib/python3.3/site-packages/requests/packages/urllib3/util/connection.py", line 78, in create_connection
    sock.connect(sa)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', TimeoutError(60, 'Operation timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/errr/venvs/pvc/lib/python3.3/site-packages/pvc/core.py", line 122, in login
    self.agent.connect()
  File "/Users/errr/venvs/pvc/lib/python3.3/site-packages/vconnector/core.py", line 127, in connect
    pwd=self.pwd
  File "/Users/errr/venvs/pvc/lib/python3.3/site-packages/pyVim/connect.py", line 577, in SmartConnect
    preferredApiVersions)
  File "/Users/errr/venvs/pvc/lib/python3.3/site-packages/pyVim/connect.py", line 520, in __FindSupportedVersion
    path)
  File "/Users/errr/venvs/pvc/lib/python3.3/site-packages/pyVim/connect.py", line 435, in __GetServiceVersionDescription
    sock = requests.get(url, verify=False)
  File "/Users/errr/venvs/pvc/lib/python3.3/site-packages/requests/api.py", line 68, in get
    return request('get', url, **kwargs)
  File "/Users/errr/venvs/pvc/lib/python3.3/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/Users/errr/venvs/pvc/lib/python3.3/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/errr/venvs/pvc/lib/python3.3/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/Users/errr/venvs/pvc/lib/python3.3/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', TimeoutError(60, 'Operation timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/errr/venvs/pvc/bin/pvc-tui", line 39, in <module>
    main()
  File "/Users/errr/venvs/pvc/bin/pvc-tui", line 36, in main
    app.run()
  File "/Users/errr/venvs/pvc/lib/python3.3/site-packages/pvc/core.py", line 139, in run
    if not self.login():
  File "/Users/errr/venvs/pvc/lib/python3.3/site-packages/pvc/core.py", line 134, in login
    text='Failed to login to {}\n\n{}\n'.format(self.agent.host, e.msg)
AttributeError: 'ConnectionError' object has no attribute 'msg'
```

**Comment by dnaeon** [comment]
@michaelrice, can you please test the latest PVC release from the Github repository and let me know how it works now?

Thanks,
Marin

**Comment by michaelrice** [comment]
Sure, Ill pull it down this afternoon and see how it goes.

**Comment by michaelrice** [comment]
It now fails gracefully as I would expect. Thanks for the quick turn-around on this @dnaeon

**Comment by dnaeon** [comment]
Thanks for testing and confirming!
